In [ ]:
# remember that commas are what defines a tuple and not the parenthesis
a = 10, 20, 30
print(isinstance(a, tuple))

# Though remember that it is good to use it since sometimes when passing tuples
# as parameters a parenthesis is actually the best way to define them.
print(1,2,3) # not a tuple
print((1, 2, 3)) # a tuple

True
1 2 3
(1, 2, 3)

In [ ]:
# we can use all operations valid on sequences like
a = 1, 2, 3, 4, 5

# slicing
a[:3]

# iterate 
for e in a:
  print(e)

# unpack, 
a, b, *_, d = a

# tuples are immutable which mean that we cannot modify the object by adding or removing
# but the objects inside the tuple could be mutable.

1
2
3
4
5

In [ ]:
# Since tuples are immutable we can leverage this by using them as data structures
# the caveat is that we must document what each position is so a user would be
# able to reference the data correctly.

london = 'London', 'UK', 8_750_000
new_york = 'New York', 'USA', 8_500_000
beijing = 'Beijing', 'China', 21_000_000

cities = [london, new_york, beijing]

sum(city[2] for city in cities)

38250000

In [ ]:
import random
from random import uniform
from math import sqrt

def random_shot(radius):
  random_x = uniform(-radius, radius)
  random_y = uniform(-radius, radius)

  if sqrt(random_x ** 2 + random_y **2) <= radius:
    is_in_circle = True
  else:
    is_in_circle = False

  return random_x, random_y, is_in_circle

In [ ]:
num_attrmps = 1000000
count_inside = 0
for i in range(num_attrmps):
  *_, is_in_circle = random_shot(1)
  if is_in_circle:
    count_inside += 1

print(f"pi is approximately {4 * count_inside / num_attrmps}")

pi is approximately 3.142888

In [ ]:
# Named tuples are created to address this.
class Point3D:
  def __init__(self, x, y, z):
    self.x = x
    self.y = y
    self.z = z
  
  def __repr__(self):
    return f"{self.__class__.__name__}(x={self.x}, y={self.y}, z={self.z})"

  def __eq__(self, other):
    if isinstance(other, Point3D):
      return self.x == other.x and self.y == other.y and self.z == other.y
    else:
      return False

# we sometimes find ourselves doing this, creating classes to store
# data with related attributes, this is where named tuples come in to play
# they inherit from tuple but add functionality specified to name the index
# entry to work as a class. in addition as they are immutable it would sometimes
# be safer too to use them instead of a class.

from collections import namedtuple

In [ ]:
Point2D = namedtuple('Point2D', ['x', 'y']) # the name of the class is Point2D defined inside
# it is useful to name the varriable that points to the object the same to instantiate the objects
# Namedtuple is just a class factory. that means it returns the class to instantiate the objects.
pnt_1 = Point2D(1, 2)
print(pnt_1) # has the __repr__ already set up for us.

Point2D(x=1, y=2)

In [ ]:
# now since tuples implement the __eq__ and named tuples inherit from them we can use that
pnt_1 = Point2D(1, 2)
pnt_2 = Point2D(1, 2)
print(pnt_1 == pnt_2)

True

In [ ]:
# we could also get the max() for the tuples.
print(max(pnt_1))

2

In [ ]:
# one example is dot product
# a . b = a.x * b.x + a.y * b.y
def dot_product_3d(a, b):
  return a.x * b.x + a.y * b.y + a.z * b.z

print(dot_product_3d(Point3D(1, 2, 3), Point3D(4, 5, 6)))

32

In [ ]:
# the same with named tuples
def dot_product(a, b):
  return sum(e[0] * e[1] for e in zip(a, b))

dot_product(pnt_1, pnt_2)
# the thing is that now it works for 2, 3,... dimensions

Point3D = namedtuple('Point3D', ['x', 'y', 'z'])
p1 = Point3D(1,2,3)
p2 = Point3D(1,2,3)
print(dot_product(p1, p2))

14

In [ ]:
# we CAN'T give names that start with _ on named tuples, unless we set
# rename to True, however it only modifies the wrong variables names and
# sets one. (the namedtuples uses _ named fields that's why we can't set them)
Person = namedtuple('Person', 'name _year', rename=True)
print(Person._fields)

# Also we can check what and how the tuples is implemented
# print(Person._source)


# we can also cast it to a ordered dict
print(pnt_1._asdict()) # we use a ordered dict for conserving the order in which they were entered, 
# however now the implementation of dicts use this.

('name', '_1')
OrderedDict([('x', 1), ('y', 2)])

In [2]:
# Modifying and extending
# not mutating though, they are immutable
from collections import namedtuple
Point2D = namedtuple('Point2D', 'x y')

In [7]:
# to modify a value in a namedtuple we could do as follows
p1 = Point2D(1,2)
p1 = Point2D(2, p1.y) # we have to create a new tuple.

# however this has drawbacks when we have longer tuples and we want to 
# modify a middle value
Stock = namedtuple('Stock', 'symbol year month day open high low close')
djia = Stock('DJIA', 2018, 1, 25, 26_313, 26_458, 26_260, 26_393)

djia = Stock(djia.symbol, 2019, djia.month, djia.day, djia.open, djia.high,
             djia.low, djia.close) # this is bothersome to write.

# if we needed to modify one of the lasts or first we could unpack it but that
# too gets cumbersome real fast.
*values, _ = djia
djia = Stock(*values, 1000)
# we could also achieve this same by using the _make method which receives an 
# iterable as input.
djia = Stock._make(tuple(values) + (100,))

print(djia.close)

100

In [5]:
# for replacing there is a built in method in the namedtuple object which would
# actually get the key-value pair as input.
djia = djia._replace(year=2018, close=3)
print(djia.year, djia.close)

# it returns a new tuple since it is still immutable.

2018 3

In [9]:
# to add fields we could create just a new one with the values from the previous,
# by using the _fields attribute.
Point3D = namedtuple('Point3D', Point2D._fields + ('z',))
# now to actually "update" an existing 2d to 3d we would
pt3d = Point3D(*p1, 100)

In [ ]:
# Docstrings and default values.
Point2D = namedtuple('Point2D', 'x y')
# We have some attributes to use.
# docstring.
print(Point2D.__doc__)
# attributes docs
print(Point2D.x.__doc__)

# Now this just calls 
help(Point2D)

# now docstrings are not only readable, we can set them and override them.

In [15]:
# for defaults we could have as follows
Vector2D = namedtuple('Vector2D', 'x1 y1 x2 y2 origin_x origin_y')

# we could use a prototype to set some defaults for origins.
vector_zero = Vector2D(0, 0, 0, 0, 0, 0)

# now to create new ones we use this prototype.
v2 = vector_zero._replace(x1=1, x2=2, y1=4, y2=4)
print(v2)

Vector2D(x1=1, y1=4, x2=2, y2=4, origin_x=0, origin_y=0)

In [19]:
# now this approach works but its not the best solution. we can make use of 
# __defaults to set them.
def func(a, b=1, c=2):
  print(a, b, c)

func.__defaults__
# we can see this used by mapping the latest one in the tuple to the one in the right
# we now move to the left until we tun out.
Vector2D.__new__.__defaults__ = 0, 0
v2 = Vector2D(1,1,2,3) # now we have the defaults.
v2

Vector2D(x1=1, y1=1, x2=2, y2=3, origin_x=0, origin_y=0)

In [22]:
# applications
from random import randint, random

Color = namedtuple('Color', 'red green blue alpha')

def random_color():
  red = randint(0, 255)
  green = randint(0, 255)
  blue = randint(0, 255)
  alpha = round(random(), 2)
  return Color(red, green, blue, alpha) # this is useful when using an IDE since
  # it will inspect the namedtuple and get more accurate description.

color = random_color()

In [27]:
# alternative to dicts.
# useful too when having lists of dicts.
# map to the .get on dicts.
getattr(color, 'red', None)

data_list = [
    {'key1':1, 'key2': 2},
    {'key1':3, 'key2': 4},
    {'key1':5, 'key2': 6, 'key3': 7},
    {'key2': 100}
]
keys = set()
keys = {key for dict_ in data_list for key in dict_.keys()}

print(keys) # this just gets the unique keys.


# now the name tuple
Struct = namedtuple('Struct', sorted(keys))

# now defaults (None)
Struct.__new__.__defaults__ = (None, ) * len(Struct._fields)

tuple_list = [Struct(**dict_) for dict_ in data_list]
print(tuple_list)

{'key3', 'key2', 'key1'}
[Struct(key1=1, key2=2, key3=None), Struct(key1=3, key2=4, key3=None), Struct(key1=5, key2=6, key3=7), Struct(key1=None, key2=100, key3=None)]